site_name: Bake a cake
repo_url: https://github.com/le-quoc-tuan/bake-a-cake
repo_name: GitHub
site_description: Huong dan tim hieu CakePHP
site_author: Le Quoc Tuan - 22dfly@gmail.com
theme: readthedocs
pages:
- Mở đầu:
    - Giới thiệu chung: index.md
    - Mô hình MVC: overview/request.md
- Cài đặt:
    - XAMPP: install/xampp.md
    - CakePHP: install/cakephp.md
    - Hello world: install/hello_world.md
    - Cấu trúc thư mục: install/folder_structure.md
- Cơ bản:
    - Route: basic/route.md
    - Controller: basic/controller.md
    - Model: basic/model.md
    - View: basic/view.md
- Nâng cao:
    - Controller
    - Model
    - View
- Tài liệu tham khảo
